### ISSUE TITLE
NullPointerException on startup

### ISSUE THREAD

**Issue by funkey** [saalfeldlab/bigcat#11]
I think it is related to recent changes in label interpolation:

https://github.com/saalfeldlab/bigcat/commit/7ae3baec0751131473a6c61fdfdbb40b55536174

```
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:293)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
    at bdv.img.cache.VolatileGlobalCellCache.createGlobal(VolatileGlobalCellCache.java:528)
    at bdv.img.cache.VolatileGlobalCellCache$VolatileCellCache.load(VolatileGlobalCellCache.java:653)
    at bdv.img.cache.VolatileImgCells$CachedCells.get(VolatileImgCells.java:110)
    at bdv.img.cache.VolatileImgCells$CachedCells.get(VolatileImgCells.java:92)
    at net.imglib2.img.list.ListRandomAccess.get(ListRandomAccess.java:81)
    at net.imglib2.img.cell.CellRandomAccess.getCell(CellRandomAccess.java:130)
    at net.imglib2.img.cell.CellRandomAccess.updatePosition(CellRandomAccess.java:470)
    at net.imglib2.img.cell.CellRandomAccess.<init>(CellRandomAccess.java:124)
    at net.imglib2.img.cell.AbstractCellImg.randomAccess(AbstractCellImg.java:126)
    at net.imglib2.img.cell.AbstractCellImg.randomAccess(AbstractCellImg.java:48)
    at net.imglib2.outofbounds.AbstractOutOfBoundsValue.<init>(AbstractOutOfBoundsValue.java:83)
    at net.imglib2.outofbounds.OutOfBoundsConstantValue.<init>(OutOfBoundsConstantValue.java:60)
    at net.imglib2.outofbounds.OutOfBoundsConstantValueFactory.create(OutOfBoundsConstantValueFactory.java:71)
    at net.imglib2.outofbounds.OutOfBoundsConstantValueFactory.create(OutOfBoundsConstantValueFactory.java:48)
    at net.imglib2.view.ExtendedRandomAccessibleInterval.randomAccess(ExtendedRandomAccessibleInterval.java:75)
    at net.imglib2.view.ExtendedRandomAccessibleInterval.randomAccess(ExtendedRandomAccessibleInterval.java:54)
    at net.imglib2.interpolation.randomaccess.NearestNeighborInterpolator.<init>(NearestNeighborInterpolator.java:75)
    at net.imglib2.interpolation.randomaccess.NearestNeighborInterpolatorFactory.create(NearestNeighborInterpolatorFactory.java:57)
    at net.imglib2.interpolation.randomaccess.NearestNeighborInterpolatorFactory.create(NearestNeighborInterpolatorFactory.java:52)
    at net.imglib2.interpolation.Interpolant.realRandomAccess(Interpolant.java:70)
    at net.imglib2.realtransform.RealTransformRealRandomAccessible$RealTransformRealRandomAccess.<init>(RealTransformRealRandomAccessible.java:76)
    at net.imglib2.realtransform.AffineRealRandomAccessible$AffineRealRandomAccess.<init>(AffineRealRandomAccessible.java:69)
    at net.imglib2.realtransform.AffineRealRandomAccessible.realRandomAccess(AffineRealRandomAccessible.java:267)
    at net.imglib2.realtransform.AffineRealRandomAccessible.realRandomAccess(AffineRealRandomAccessible.java:55)
    at bdv.bigcat.MergeController.<init>(MergeController.java:100)
    at bdv.bigcat.BigCATAriadne.main(BigCATAriadne.java:161)
    ... 6 more
```

Occured when launching BigCATAriadne.java.

**Comment by funkey** [comment]
Solved in current master.
